### ISSUE TITLE
A Blank "Send Commands" bar should send an Enter/Return to All or Selected sessions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#490]
```
When faced with sessions prompts to confirm information, such as a Reload 
command on Cisco devices returning with:

SW1#reload <User:reload>
System configuration has been modified. Save? [yes/no]: n <User:n>
Proceed with reload? [confirm]    <User:"Enter" key>

The "Send Commands" bar should send a Return to all open sessions.

----

If no input is provided, still send Enter/Return

```

Original issue reported on code.google.com by `scottbri...@gmail.com` on 16 Dec 2014 at 6:46

**Comment by darkstar** [comment]
There's still something funny going on with sending a single CR to all sessions.

When you first send a specific command to a session (or, say, a username and password), the input box at the top will become empty after every sent command. However, if you then press just "enter", SuperPutty repeatedly sends the last commands entered again instead of an empty string. i.e. typing "root<enter>", "myrootpassword<enter>", "<enter>", "<enter>" into the command box, you end up with "root<enter>myrootpassword<enter>root<enter>myrootpassword<enter>" in the puTTY session, which is obviously not what you'd want.

if you go back to the input box, type a single space and then erase it and press enter, then a plain <enter> is sent to all sessions as expected

**Comment by larsen0815** [comment]
I can confirm this problem: Clicking on the green icon puts the last used commands onto the shell, but doesn't execut it. Pressing enter inside the empty (!) box executes the last commands. Afterwards, clicking the green icon didn't do anything, anymore.
