### ISSUE TITLE
plugins for SuperPutty? Active Directory query of server to get FQDN?

### ISSUE THREAD

**Issue by imthenachoman** [jimradford/superputty#532]
Hello. I wasn't sure how to contact you so I thought I would try here. I have two questions:

 1. Any plans to add the ability to develop/use plugins with SuperPutty?
 2. Any plans to add functionality that would query AD for a server name to obtain it's FQDN to connect to?

I don't know C# or I would modify the code myself so I thought I would ask..

**Comment by jimradford** [comment]
@imthenachoman 
1) There are no immediate plans to implement a plugin architecture other than I have done some work on a plugin system for session management (e.g a plugin could be implemented to support saving sessions to/from a remote web server).

2) Not currently even looked at. That would be difficult to implement since I have no AD server to test against.

Regards,
Jim

**Comment by imthenachoman** [comment]
Understood @jimradford. Thanks!
