### ISSUE TITLE
Enhancements for FileTransfer window

### ISSUE THREAD

**Issue by beirtipol** [jimradford/superputty#561]
There are some simple features/improvements that would make SuperPutty more usable as a WinSCP standin. Wanted to check which are feasible rather than raising as separate issues.

- Allow typing the path in to the 'address' bar on local & remote
- Just default to "c:\" and "/" as the directories to open on each side to save having to set a 'home prefix'
- Allow basic file operations on local & remote with a context menu (view/rename/create file or folder/copy/paste/move, chmod)
- Optional Tree panel for directory structure on each side of a connection
- Open in 'explorer' mode to show just the remote side and allow dragging and dropping in to windows explorer.
- Speed of navigation seems very slow

**Comment by jimradford** [comment]
- [x] Allow typing the path in to the 'address' bar on local & remote
**Yes** This can be done, open a separate issue on this

- [x] Just default to "c:\" and "/" as the directories to open on each side to save having to set a 'home prefix'
**Yes** This can be added as an option in settings. Please open a new issue for this request.

- [ ] Allow basic file operations on local & remote with a context menu (view/rename/create file or folder/copy/paste/move, chmod)
**No** PSCP does not support these types of operations, PSFTP however does.

- [ ] Optional Tree panel for directory structure on each side of a connection
**Maybe** This would take considerable work since pscp connections are short lived, e.g. we make a connection, do an operation (list, or transfer) and exit. It would require caching the remote folder contents

- [ ] Open in 'explorer' mode to show just the remote side and allow dragging and dropping in to windows explorer.
See above answer

- [ ] Speed of navigation seems very slow
**Sorry** this is an inherent limitation of using pscp. A future implementation might require using a library such as the one provided by winscp to become a full fledged client.

PSFTP differs from PSCP in the following ways:

    PSCP should work on virtually every SSH server. PSFTP uses the new SFTP protocol, which is a feature of SSH 2 only. (PSCP will also use this protocol if it can, but there is an SSH 1 equivalent it can fall back to if it cannot.)
    PSFTP allows you to run an interactive file transfer session, much like the Windows ftp program. You can list the contents of directories, browse around the file system, issue multiple get and put commands, and eventually log out. By contrast, PSCP is designed to do a single file transfer operation and immediately terminate.

I would **love** to eventually implement better file transfer functionality, our pscp support was initially a quick dirty implementation that I didn't really think anyone besides myself would use. It seems to be a feature people do like and use even with its current limitations.

**Comment by beirtipol** [comment]
Makes sense now. I'm guessing you don't fancy switching over to psftp? Admittedly it would turn it in to a full FTP file manager app but you would certainly end up as a market leader if you offer the flexible windows, sessions with console and remote file management. (dream app)

Will open separate issues for the other requests, thanks.

**Comment by jimradford** [comment]
@beirtipol The main issue is backwards compatibility, pscp supports both ssh1 and ssh2, psftp only supports ssh2, so there would be considerable amount of work supporting both which quite frankly could be better spend on a better implementation for file transfers in general. I am not opposed to this now its just a matter of finding the time. Personally I normally use winscp for most file transfers.

Thanks again for the feedback and ideas!
