### ISSUE TITLE
Password field in toolbar "quick connection" does not work anymore

### ISSUE THREAD

**Issue by Sephiburp** [jimradford/superputty#595]
Hi,

Until release 1.4.0.7, I filled just once my login & password into the toolbar "quick connection" and SuperPutty managed to pass them to hosts.

That does not work anymore in 1.4.0.8 for the password.
I must always re-enter the password into the terminal (the login name is still correctly auto-filled).

Maybe it's related to the fixed issue #546, if so, I don't understand how to force SuperPutty to automatically fills the password like it did before 1.4.0.8.

**Comment by ajshastri** [comment]
I looked at issue  #546 ,  jimradford's comment on Oct 26, 2015

"By default the -pw argument cannot be sent to putty now. This can be overridden in tools->options->GUI to allow this unsafe behavior"

I tried the above and was able have the functionality work again. Kinda weird tho, it should be the other way. You should need to opt out of that behavior. Otherwise I would assume it makes sense to remove the bar altogether and put it back when the option is checked. 

my 2 cents

**Comment by Sephiburp** [comment]
Hi,
Ok it works  (option "Allow plain text passwords on putty command line").
Don't know why I didn't succeed to make it work last time...
Thanks.

**Comment by kitsirota** [comment]
+1 Thanks for the tip, I was having trouble with this too.

**Comment by ramkadiveti** [comment]
Thanks Sephiburp

**Comment by Starksm** [comment]
Thanks

**Comment by PolarBearGod** [comment]
Can we move to close this "issue"? The resolution is to allow the unsafe behavior in the settings.
