### ISSUE TITLE
Window Snapping Does Not Work

### ISSUE THREAD

**Issue by calvertdw** [jimradford/superputty#661]
Win + Left/Right doesn't work. Have to drag the window to the edge of the screen. It's odd this doesn't work.

**Comment by sharpe5** [comment]
Windows snapping does work, if you click on any part of the SuperPuTTY window surrounding each terminal.

The reason is that superputty loads up instances of "putty.exe" for each individual terminal tab, and these instances do not pass the Win+Left/Right commands up to the parent SuperPuTTY process.

**Comment by splitice** [comment]
With the current build even dragging doesnt work.

![image](https://user-images.githubusercontent.com/468579/125450575-d2cab40d-f2e2-47b0-b726-b70875e1f350.png)

**Comment by splitice** [comment]
After much investigation this relates to https://github.com/dockpanelsuite/dockpanelsuite/issues/110

Unfortuantely unless @jimradford wants to use a different docking library or fix that one there isnt a huge amount that can be done.
