### ISSUE TITLE
Requesting Linux support

### ISSUE THREAD

**Issue by vias79** [jimradford/superputty#679]
This is a very nice putty windows manager.

As putty exists as native linux package, could superputty also be given linux support?

**Comment by jimradford** [comment]
@vias, this is not likely something we'll support as the window management library we utilize uses native win32 api calls, so its not easily portable to other platforms.

**Comment by avindra** [comment]
+1. The win32 usage makes it tough.

[WinForms](https://github.com/dotnet/winforms) is open source now, however WinForms development has been geared towards intuitive use of Win32 apis rather than transparently shimming the forms across multiple platforms.

I would like to see Winforms get to the point where you can use it with the native .NET build toolchain on Linux. Then it would be pretty compelling to support (i.e., you don't have to bring Mono into your build environment). And we can build cross-platform desktop apps in C#. Hope Microsoft realizes the potential...
