### ISSUE TITLE
Menu items "Edit sessions" and "Reload sessions"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#82]
```
It would be nice to have 2 new menu items: One for opening Sessions.XML in 
notepad and another for reloading Sessions.XML. With that it would be easier to 
manually edit the file without knowing it's location.
```

Original issue reported on code.google.com by `breker.c...@gmail.com` on 4 May 2012 at 9:25

**Comment by Dave-hardisty** [comment]
Hi
i've used the export/import option to get the sessions.xml but because i have moved it between computers so much i know have a file structure with 5 "imported" folders before we see my sessions, been trying to edit the xml without any luck, any help appreciated.

"Imported/Imported/Imported/Imported/Imported/Data Centres/
